In [1]:

import numpy as np 
import pandas as pd

/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv


In [2]:

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import scipy.stats as stats
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import recall_score, accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
from sklearn.feature_selection import SelectKBest
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
import matplotlib.ticker as mtick 

In [3]:
data = pd.read_csv('/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv')
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [5]:
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

In [6]:
numerical_feature = {feature for feature in data.columns if data[feature].dtypes != 'O'}
print(f'Count of Numerical feature: {len(numerical_feature)}')
print(f'Numerical feature are:\n {numerical_feature}')

Count of Numerical feature: 4
Numerical feature are:
 {'MonthlyCharges', 'SeniorCitizen', 'tenure', 'TotalCharges'}


In [30]:
Log_reg = LogisticRegression(C=150, max_iter=150)
Log_reg.fit(X_train, y_train)
log_pred = Log_reg.predict(X_test)

print(f'Accuracy score : {accuracy_score(log_pred, y_test)}')
print(f'Confusion matrix :\n {confusion_matrix(log_pred, y_test)}')
print(f'Classification report :\n {classification_report(log_pred, y_test)}')

Accuracy score : 0.8133427963094393
Confusion matrix :
 [[936 151]
 [112 210]]
Classification report :
               precision    recall  f1-score   support

           0       0.89      0.86      0.88      1087
           1       0.58      0.65      0.61       322

    accuracy                           0.81      1409
   macro avg       0.74      0.76      0.75      1409
weighted avg       0.82      0.81      0.82      1409



In [31]:
# 隨機森林
Rfc = RandomForestClassifier(n_estimators=120,criterion='gini', max_depth=15, min_samples_leaf=10, min_samples_split=5)
Rfc.fit(X_train, y_train)
rfc_pred = Rfc.predict(X_test)

print(f'Accuracy score : {accuracy_score(rfc_pred, y_test)}')
print(f'Confusion matrix :\n {confusion_matrix(rfc_pred, y_test)}')
print(f'Classification report :\n {classification_report(rfc_pred, y_test)}')

Accuracy score : 0.8197303051809794
Confusion matrix :
 [[963 169]
 [ 85 192]]
Classification report :
               precision    recall  f1-score   support

           0       0.92      0.85      0.88      1132
           1       0.53      0.69      0.60       277

    accuracy                           0.82      1409
   macro avg       0.73      0.77      0.74      1409
weighted avg       0.84      0.82      0.83      1409



In [32]:
#决策树
Dtc = DecisionTreeClassifier(criterion='gini', splitter='random', min_samples_leaf=15)
Dtc.fit(X_train, y_train)
dtc_pred = Dtc.predict(X_test)

print(f'Accuracy score : {accuracy_score(dtc_pred, y_test)}')
print(f'Confusion matrix :\n {confusion_matrix(dtc_pred, y_test)}')
print(f'Classification report :\n {classification_report(dtc_pred, y_test)}')

Accuracy score : 0.8041163946061036
Confusion matrix :
 [[944 172]
 [104 189]]
Classification report :
               precision    recall  f1-score   support

           0       0.90      0.85      0.87      1116
           1       0.52      0.65      0.58       293

    accuracy                           0.80      1409
   macro avg       0.71      0.75      0.73      1409
weighted avg       0.82      0.80      0.81      1409



In [33]:
BK_value = []
for x in range(1, 100):
    Knn = KNeighborsClassifier(n_neighbors=x, p=2)
    Knn.fit(X_train, y_train)
    knn_pred = Knn.predict(X_test)
    BK_value.append(np.mean(knn_pred != y_test))

In [35]:
Knn = KNeighborsClassifier(n_neighbors=64, p=2)
Knn.fit(X_train, y_train)
knn_pred = Knn.predict(X_test)

In [36]:
print(f'Accuracy score : {accuracy_score(knn_pred, y_test)}')
print(f'Confusion matrix :\n {confusion_matrix(knn_pred, y_test)}')
print(f'Classification report :\n {classification_report(knn_pred, y_test)}')

Accuracy score : 0.8126330731014905
Confusion matrix :
 [[962 178]
 [ 86 183]]
Classification report :
               precision    recall  f1-score   support

           0       0.92      0.84      0.88      1140
           1       0.51      0.68      0.58       269

    accuracy                           0.81      1409
   macro avg       0.71      0.76      0.73      1409
weighted avg       0.84      0.81      0.82      1409



In [37]:
st=SMOTEENN()
X_train_st,y_train_st = st.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_st)))

The number of classes before fit Counter({0: 4126, 1: 1508})
The number of classes after fit Counter({0: 2441, 1: 2416})


In [38]:
# 拆分数据集
X_train_sap, X_test_sap, y_train_sap, y_test_sap = train_test_split(X_train_st, y_train_st, test_size=0.2)

In [39]:
#决策树优化
Dtc_sampling = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=7, min_samples_leaf=15)
Dtc_sampling.fit(X_train_sap, y_train_sap)
dtc_sampling_pred = Dtc_sampling.predict(X_test_sap)

print(f'Accuracy score : {accuracy_score(dtc_sampling_pred, y_test_sap)}')
print(f'Confusion matrix :\n {confusion_matrix(dtc_sampling_pred, y_test_sap)}')
print(f'Classification report :\n {classification_report(dtc_sampling_pred, y_test_sap)}')

Accuracy score : 0.9300411522633745
Confusion matrix :
 [[447  25]
 [ 43 457]]
Classification report :
               precision    recall  f1-score   support

           0       0.91      0.95      0.93       472
           1       0.95      0.91      0.93       500

    accuracy                           0.93       972
   macro avg       0.93      0.93      0.93       972
weighted avg       0.93      0.93      0.93       972



In [40]:
# Random forest classifier
Rfc_sampling = RandomForestClassifier(n_estimators=150,criterion='gini', max_depth=15, min_samples_leaf=10, min_samples_split=6)
Rfc_sampling.fit(X_train_sap, y_train_sap)
rfc_sampling_pred = Rfc_sampling.predict(X_test_sap)

print(f'Accuracy score : {accuracy_score(rfc_sampling_pred, y_test_sap)}')
print(f'Confusion matrix :\n {confusion_matrix(rfc_sampling_pred, y_test_sap)}')
print(f'Classification report :\n {classification_report(rfc_sampling_pred, y_test_sap)}')

Accuracy score : 0.9444444444444444
Confusion matrix :
 [[463  27]
 [ 27 455]]
Classification report :
               precision    recall  f1-score   support

           0       0.94      0.94      0.94       490
           1       0.94      0.94      0.94       482

    accuracy                           0.94       972
   macro avg       0.94      0.94      0.94       972
weighted avg       0.94      0.94      0.94       972



In [41]:
Log_reg_sampling = LogisticRegression(C=10, max_iter=150)
Log_reg_sampling.fit(X_train_sap, y_train_sap)
Log_sampling_pred = Log_reg_sampling.predict(X_test_sap)

print(f'Accuracy score : {accuracy_score(Log_sampling_pred, y_test_sap)}')
print(f'Confusion matrix :\n {confusion_matrix(Log_sampling_pred, y_test_sap)}')
print(f'Classification report :\n {classification_report(Log_sampling_pred, y_test_sap)}')

Accuracy score : 0.9259259259259259
Confusion matrix :
 [[447  29]
 [ 43 453]]
Classification report :
               precision    recall  f1-score   support

           0       0.91      0.94      0.93       476
           1       0.94      0.91      0.93       496

    accuracy                           0.93       972
   macro avg       0.93      0.93      0.93       972
weighted avg       0.93      0.93      0.93       972



In [42]:
Knn_sampling = KNeighborsClassifier(n_neighbors=3, p=2)  
Knn_sampling.fit(X_train_sap, y_train_sap)
knn_sampling_pred = Knn_sampling.predict(X_test_sap)

print(f'Accuracy score : {accuracy_score(knn_sampling_pred, y_test_sap)}')
print(f'Confusion matrix :\n {confusion_matrix(knn_sampling_pred, y_test_sap)}')
print(f'Classification report :\n {classification_report(knn_sampling_pred, y_test_sap)}')

Accuracy score : 0.9763374485596708
Confusion matrix :
 [[472   5]
 [ 18 477]]
Classification report :
               precision    recall  f1-score   support

           0       0.96      0.99      0.98       477
           1       0.99      0.96      0.98       495

    accuracy                           0.98       972
   macro avg       0.98      0.98      0.98       972
weighted avg       0.98      0.98      0.98       972

